project.radios = [
    {
        "id": 1,
        "name": "104.8",
        "tagline": "CLUB FM",
        "color": "0xffa11431",
        "desc": "The chills you get when you listen to music, is mostly caused by the brain releasing dopamine while anticipating the peak moment of a song.",
        "url": "https://eu10.fastcast4u.com/clubfmuae",
        "icon": "https://onlineradiofm.in/assets/image/radio/180/clubfmnewlogo.jpg",
        "image": "https://onlineradiofm.in/assets/image/radio/180/clubfmnewlogo.jpg",
        "lang": "Malayalam",
        "category": "pop",
        "disliked": false,
        "order": 1
    },
    {
        "id": 2,
        "name": "98.6",
        "tagline": "RADIO 98.6",
        "color": "0xff221420",
        "desc": "There are few activities in life that utilizes the entire brain, and music is one of them.",
        "url": "http://vokcast.bluecast.in:8227/986fm",
        "icon": "https://1.bp.blogspot.com/-c4UT7dJQJWI/WvUnm-peNrI/AAAAAAAAHLs/pN3c48ylLRcg9C_J_rfvikwcUpjRtk9NgCLcBGAs/s200/Radio%2B98.6%2BMalayalam%2BFM%2BQatar%2BLive%2BStreaming%2BOnline.jpg",
        "image": "https://1.bp.blogspot.com/-c4UT7dJQJWI/WvUnm-peNrI/AAAAAAAAHLs/pN3c48ylLRcg9C_J_rfvikwcUpjRtk9NgCLcBGAs/s200/Radio%2B98.6%2BMalayalam%2BFM%2BQatar%2BLive%2BStreaming%2BOnline.jpg",
        "lang": "Malayalam",
        "disliked": false,
        "category": "rock",
        "order": 2
    },
    {
        "id": 3,
        "name": "101.3",
        "tagline": "GOLD 4",
        "color": "0xff04080b",
        "desc": "Playing music regularly will physically alter your brain structure.",
        "url": "http://streams.radio.co/s909325731/listen",
        "icon": "https://cdn-radiotime-logos.tunein.com/s133137g.png",
        "image": "https://cdn-radiotime-logos.tunein.com/s133137g.png",
        "lang": "Malayalam",
        "disliked": false,
        "category": "hip-hop",
        "order": 3
    },
    {
        "id": 4,
        "name": "101.9",
        "tagline": "ANANTHAPURI FM",
        "color": "0xff066c53",
        "desc": "അനന്തപുരിയുടെ ഹൃദയതാളം",
        "url": "http://59.90.28.91:88/broadwavelow.mp3?src=1",
        "icon": "https://cdn-profiles.tunein.com/s281843/images/logod.jpg?t=156621",
        "image": "https://cdn-profiles.tunein.com/s281843/images/logod.jpg?t=156621",
        "lang": "Malayalam",
        "category": "classic",
        "disliked": false,
        "order": 4
    },
    {
        "id": 5,
        "name": "94.7",
        "tagline": "RADIO ASIA",
        "color": "0xff0d487d",
        "desc": "",
        "url": "http://51.255.235.165:5480/;stream.mp3",
        "icon": "https://pea.fm/uploads/posts/2020-07/1594810506_radio-asia-94_7-fm.png",
        "image": "https://pea.fm/uploads/posts/2020-07/1594810506_radio-asia-94_7-fm.png",
        "lang": "Malayalam",
        "category": "jazz",
        "disliked": false,
        "order": 5
    },
//     {
//         "id": 6,
//         "name": "94",
//         "tagline": "Today's Hits",
//         "color": "0xff27383e",
//         "desc": "",
//         "url": "http://playerservices.streamtheworld.com/api/livestream-redirect/977_HITS.mp3",
//         "icon": "https://static.radio.net/images/broadcasts/8d/76/3600/1/c175.png",
//         "image": "https://i.ytimg.com/vi/BUnPVjqb0YY/maxresdefault.jpg",
//         "lang": "English",
//         "category": "rock",
//         "disliked": false,
//         "order": 6
//     },
    {
        "id": 6,
        "name": "91.7",
        "tagline": "RADIO SUNO",
        "color": "0xffa06a37",
        "desc": "The brain responds to music the same way it responds to something that you eat.",
        "url": "http://playerservices.streamtheworld.com/api/livestream-redirect/SUNO917_SC",
        "icon": "https://4.bp.blogspot.com/-HA6P-oS7xgw/WglCW7cdR0I/AAAAAAAAFnM/LJXE0vOzDQAbmgw85GTkFE1D3hkzSg6AQCLcBGAs/s1600/Radio%2BSuno%2B91.7%2BQatar%2BMalayalam%2BLive%2BStreaming.png",
        "image": "https://4.bp.blogspot.com/-HA6P-oS7xgw/WglCW7cdR0I/AAAAAAAAFnM/LJXE0vOzDQAbmgw85GTkFE1D3hkzSg6AQCLcBGAs/s1600/Radio%2BSuno%2B91.7%2BQatar%2BMalayalam%2BLive%2BStreaming.png",
        "lang": "Malayalam",
        "category": "pop",
        "disliked": false,
        "order": 7
    }
//     {
//         "id": 8,
//         "name": "107",
//         "tagline": "Rocking Retro Hits",
//         "color": "0xff090909",
//         "desc": "Your heartbeat changes to mimics the music you listen to.",
//         "url": "https://bcovlive-a.akamaihd.net/19b535b7499a4719a5c19e043063f5d9/ap-southeast-1/6034685947001/profile_2/8qza59sn_7bd68a0e64284b3196b06363e9931ea0_media_122968.aac",
//         "icon": "https://mytuner.global.ssl.fastly.net/media/tvos_radios/uvclzz6a6d7x.jpeg",
//         "image": "https://i.pinimg.com/originals/7f/f6/13/7ff613ed815f1eb56a90794ec64eecfe.jpg",
//         "lang": "Hindi",
//         "category": "classic",
//         "disliked": false,
//         "order": 8
//     }
];