# Generated by Django 3.0.8 on 2022-06-20 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('u_id', models.AutoField(primary_key=True, serialize=False)),
                ('u_name', models.CharField(max_length=30)),
                ('u_mobile', models.CharField(max_length=30)),
                ('u_mail', models.CharField(max_length=50)),
                ('u_location', models.CharField(max_length=30)),
                ('u_dob', models.DateField()),
                ('u_gender', models.CharField(max_length=30)),
                ('u_uname', models.CharField(max_length=30)),
                ('u_pass', models.CharField(max_length=30)),
                ('u_profile_pic', models.CharField(max_length=500)),
                ('u_status', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
