# Generated by Django 3.0.8 on 2022-06-20 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('friend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friendrequest',
            fields=[
                ('req_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=30)),
                ('f', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='friend.Friend')),
                ('u', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
            options={
                'db_table': 'friendRequest',
            },
        ),
    ]
