# Generated by Django 4.0.5 on 2022-06-14 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_remove_answermodel_pic_remove_questionmodel_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionmodel',
            name='pic',
            field=models.ImageField(blank=True, upload_to='qnpic/'),
        ),
    ]
