# Generated by Django 4.0.5 on 2022-06-14 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_questionmodel_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionmodel',
            name='pic',
            field=models.ImageField(blank=True, upload_to='qnpic/'),
        ),
    ]
