# Generated by Django 3.0.8 on 2022-06-20 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('p_id', models.AutoField(primary_key=True, serialize=False)),
                ('p_content', models.CharField(max_length=300)),
                ('emotion', models.CharField(max_length=30)),
                ('p_pic', models.CharField(max_length=500)),
                ('p_date', models.DateField()),
                ('p_time', models.TimeField()),
                ('u', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
            options={
                'db_table': 'post',
            },
        ),
    ]
