# Generated by Django 3.2.13 on 2022-06-27 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emotion',
            fields=[
                ('em_id', models.AutoField(primary_key=True, serialize=False)),
                ('emotion', models.CharField(max_length=50)),
                ('images', models.CharField(max_length=100)),
                ('u_id', models.IntegerField()),
            ],
            options={
                'db_table': 'emotion',
                'managed': False,
            },
        ),
    ]
