# Generated by Django 4.0.5 on 2022-06-04 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_answermodel_down_vote_answermodel_up_vote_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answermodel',
            name='answer',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='questionmodel',
            name='qn',
            field=models.TextField(max_length=100),
        ),
    ]
