# Generated by Django 4.0.5 on 2022-06-16 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_questionmodel_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='answermodel',
            name='pic',
            field=models.ImageField(blank=True, upload_to='anspic/'),
        ),
    ]
