# Generated by Django 3.2.13 on 2022-06-07 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Musiclist',
            fields=[
                ('m_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('filename', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'musiclist',
                'managed': False,
            },
        ),
    ]
